# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - industrialbackend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://industrialcontainer.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_406a854ebf8c4031b5d1a15f74bcb960 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3e8421549bc54390a3b1f74c813f9e3b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: industrialcontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_406a854ebf8c4031b5d1a15f74bcb960 }}/industrial-backend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'industrialbackend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b65ba26409f842a2a71cbf4bae1c2036 }}
        images: 'industrialcontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_406a854ebf8c4031b5d1a15f74bcb960 }}/industrial-backend:${{ github.sha }}'